language: python
python:
  - "3.4"

before_install:
  - export DJANGO_SETTINGS_MODULE=webserver.webserver.settings
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - ./webserver/manage.py test # or py.test for Python versions 3.5 and below