language: python
python:
  - "3.4"

install:
  - pip install -r requirements.txt

script:
  - pytest --cov=core --cov-report xml:coverage.xml

after_success:
  - python-codacy-coverage -r coverage.xml